### PR TITLE
Added caption functinality

### PR DESCRIPTION
**Pull request by ArtStepanyuk**
-added caption functionality

title property should be present on image otherwise there wont be caption

### CODE REVIEW

**Comment by rap2hpoutre** [comment]
Thank you for your contribution! Does it still work without a title (in other words, title have to be optional and should not display a warning in console). I'm in a train for a few hours so I can't test it myself...

**Comment by ArtStepanyuk** [comment]
Hello, yes it works without the title, no errors are thrown, if there is no title property present on image object the preview won't have a caption, there is no error in console.

But it would be nice if you gave it a test run as well first before merging.

Thank you

**Comment by rap2hpoutre** [comment]
Sorry for late answer. I will try to merge it (and publish it) tomorrow.

**Comment by ArtStepanyuk** [comment]
No worries I'm glad to help

**Comment by rap2hpoutre** [comment]
Available in v0.4.0

**Pull request merged**
