### PR TITLE
added rotation option

### PR DESCRIPTION
**Pull request by ArtStepanyuk**
- added rotations functionality

### CODE REVIEW

**Comment by rap2hpoutre** [comment]
Thank you! Some questions:

 - Are you sure material design is required here? (I think it's maybe too much for two icons, I have no better idea though).
 - According to [PhotoSwipe documentation](http://photoswipe.com/documentation/options.html), the options about "UI elements" are postfixed by `El`, not `On`. So maybe we should use `rotationEl`

**Comment by ArtStepanyuk** [comment]
I just added material icons cause I like them the most :) Be free to change it to any other icons which would fit design nicely

About renaming I'm not sure if its a good idea since its optional feature so I as dev would like to have a more understandable name but if you want I can update PR with changing a name to rotationEl

Let me know what you think about icon options and renaming.

Thank you

**Comment by ArtStepanyuk** [comment]
Few ideas about icons for future. Currently, we have needed only for 2 new icons, but for new features, we would need more since we only have only photo swipe icons and functionality now but there is much more things which can be added in future and require more icons as well
example

1 slider to change the size of the picture, would need 2 more icons to show directions to left and right
2 download image(there is an icon in share functionality) But what if I want just download without the whole context menu such as share it online

Material icons are 600b big 300 if cached. So I believe adding a dependency on the icon is fine just the matter of which provider to use, font awesome or material or any other you would consider more fitting to the project

Let me know what you think about it and thank you!

**Comment by rap2hpoutre** [comment]
@ArtStepanyuk Thank you! (and thanks for your argument!)

**Pull request merged**
